service: grimdark
image: snaxmm/grimdark-web

registry:
  username: snaxmm
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
  context: web
  dockerfile: web/Dockerfile
  args:
    VITE_BACKEND_URL: https://snaxgames.app

servers:
  web:
    - 143.244.147.133

proxy:
  ssl: true
  host: snaxgames.app
  app_port: 3000
