/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpRouteImport } from './routes/up'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed.index'
import { Route as AuthedUserRouteImport } from './routes/_authed.user'
import { Route as AuthedLobbyGameIDRouteImport } from './routes/_authed.lobby.$gameID'
import { Route as AuthedBattleGameIDRouteImport } from './routes/_authed.battle.$gameID'

const UpRoute = UpRouteImport.update({
  id: '/up',
  path: '/up',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUserRoute = AuthedUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLobbyGameIDRoute = AuthedLobbyGameIDRouteImport.update({
  id: '/lobby/$gameID',
  path: '/lobby/$gameID',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBattleGameIDRoute = AuthedBattleGameIDRouteImport.update({
  id: '/battle/$gameID',
  path: '/battle/$gameID',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/up': typeof UpRoute
  '/user': typeof AuthedUserRoute
  '/battle/$gameID': typeof AuthedBattleGameIDRoute
  '/lobby/$gameID': typeof AuthedLobbyGameIDRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/up': typeof UpRoute
  '/user': typeof AuthedUserRoute
  '/': typeof AuthedIndexRoute
  '/battle/$gameID': typeof AuthedBattleGameIDRoute
  '/lobby/$gameID': typeof AuthedLobbyGameIDRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/up': typeof UpRoute
  '/_authed/user': typeof AuthedUserRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/battle/$gameID': typeof AuthedBattleGameIDRoute
  '/_authed/lobby/$gameID': typeof AuthedLobbyGameIDRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/up'
    | '/user'
    | '/battle/$gameID'
    | '/lobby/$gameID'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/up' | '/user' | '/' | '/battle/$gameID' | '/lobby/$gameID'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/up'
    | '/_authed/user'
    | '/_authed/'
    | '/_authed/battle/$gameID'
    | '/_authed/lobby/$gameID'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  UpRoute: typeof UpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/up': {
      id: '/up'
      path: '/up'
      fullPath: '/up'
      preLoaderRoute: typeof UpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/user': {
      id: '/_authed/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof AuthedUserRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/lobby/$gameID': {
      id: '/_authed/lobby/$gameID'
      path: '/lobby/$gameID'
      fullPath: '/lobby/$gameID'
      preLoaderRoute: typeof AuthedLobbyGameIDRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/battle/$gameID': {
      id: '/_authed/battle/$gameID'
      path: '/battle/$gameID'
      fullPath: '/battle/$gameID'
      preLoaderRoute: typeof AuthedBattleGameIDRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedUserRoute: typeof AuthedUserRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedBattleGameIDRoute: typeof AuthedBattleGameIDRoute
  AuthedLobbyGameIDRoute: typeof AuthedLobbyGameIDRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedUserRoute: AuthedUserRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedBattleGameIDRoute: AuthedBattleGameIDRoute,
  AuthedLobbyGameIDRoute: AuthedLobbyGameIDRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  UpRoute: UpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
